<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Factorio.Agent.Infrastructure/Factorio.Agent.Infrastructure.csproj" />
    <ProjectReference Include="../Factorio.Agent.Ollama/Factorio.Agent.Ollama.csproj" />
  </ItemGroup>
</Project>
